name: Checker

on:
  pull_request_target:
    branches: master
    types: [opened, reopened]

jobs:
  hw-checker:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check Answer
        uses: zhangt2333/action-judger@main
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          USERNAME: ${{ github.event.issue.user.login }}
        with:
          acText: |
            🎉 Congratulations! Your answer passed the CI testing!
            But this repo will not merge your PR beacuse it will be used to practice by the next user.
          script: |
            echo "1+1=2" >> ans.txt
            echo "1+2=3" >> ans.txt
            echo "1+3=4" >> ans.txt
            echo "1+4=5" >> ans.txt
            diff 1plus1.txt ans.txt -B -b -Z -w
            if [ -f 1plus2.txt ]; then exit 1; fi
